### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by Waelwindows** [CaptainDario/DaKanji-Mobile#3]
It makes it easier for people who only use FOSS apps to get your app.
It's  better to release it on the main F-Droid repository or maybe IzzyDroid's repo.

Alternatively, you could use CI to build artifacts and put them on releases in GitHub

**Comment by CaptainDario** [comment]
Thank you for the reminder to publish it on other stores too.
I will be adding it to F-Droid for sure.

Any other stores you would like have a release for?

**Comment by CaptainDario** [comment]
Because this project is strictly speaking not "open source" I cannot publish it on F-Droid (I am using a source available license).
However for the new version 1.1.0 I just published a release with APK's.
