### ISSUE TITLE
[UX] Add posibility of selecting multiple different kanji before copy/look up.

### ISSUE THREAD

**Issue by TomBPotochek** [CaptainDario/DaKanji-Mobile#4]
The gist of the idea is to have a text entry field where each subsequent selected kanji gets written to for the purpose of building up a word or short phrase before you can actually copy or look up the whole character string. That way, the experience would be more similar to using Jisho.org's kanji look up by radical or drawing (which hardly ever recognizes my strokes) and would make it much easier to look up a whole word. As it currently functions, you have to draw a kanji, copy the recognized kanji to clipboard and repeat the process for each kanji in a given word, and then paste the kanji one by one on whatever site you are using to look up the word, which becomes easily tedious.  
  
To give a bit more detail on how I'm envisioning it: after you draw the kanji and the correct character is recognized among the options, tapping the kanji would write it to a text field above or below the kanji grid and the canvass would clear. You could then draw another kanji and have the new selected kanji appended to the text on the text field, or choose to stop by having a separate button beside the text field to copy the entire string to clipboard or directly looking up the string on jisho by a long press (could also be a separate button).  
And it'd probably be useful to have the text field be directly editable by keyboard input like any regular text field.

**Comment by CaptainDario** [comment]
Thank you for the feature proposal.

I am currently working on a text field to search for complete words and it will be released in the next version (v1.1). However the idea that it should be editable with a normal keyboard is very good and will be implemented too.

**Comment by CaptainDario** [comment]
I just published v1.1.0. on Google Play. This version includes multi character search and a bunch of other improvements.
If you however think it is not what you imagined, feel free to reopen this issue.

**Comment by TomBPotochek** [comment]
Looks good. I see that you chose not to have the text field be editable with a keyboard but I think it's fair and not a big problem (or even a problem at all) so I consider this issue solved.  
By the way, love the redesign.

**Comment by CaptainDario** [comment]
@TomBPotochek I decided to not make it editable by keyboard because opening it in a dictionary/translator/etc. Will have an option to change it with keyboard for sure and this way I can use the same gestures as for the other buttons.
Additionally I am planning to add kana support to the handwriting in an upcoming version. With that words/small sentences can be written entirely with the app.
